# Generated by Django 2.2.1 on 2019-05-13 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('importance', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7)], max_length=1)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField(default=datetime.date(3000, 12, 31))),
                ('is_solved', models.BooleanField(default=False)),
            ],
        ),
    ]
