# Generated by Django 2.2.1 on 2019-05-15 03:27

from django.db import migrations, models
import todos.models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190514_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='생성 날짜'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='expired_date',
            field=models.DateField(default=todos.models.get_deadline, verbose_name='기한'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='importance',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7)], default='4', max_length=1, verbose_name='중요도'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=30, verbose_name='할 일'),
        ),
    ]
