# Generated by Django 2.2.1 on 2019-05-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190515_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['created_date']},
        ),
    ]
